# -*- coding: utf-8 -*-
"""This my very first phyton script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BqfqMcP_VBErM3lJSwuMCTUFC1yDbK_
"""

# This my very first phyton script

print ("Hello World!")

Hahahahhaha
